version: '3.8'

services:
  laravel:
    build:
      context: ./
      dockerfile: _docker/Dockerfile
      args:
        USER_ID: "1000"
        GROUP_ID: "1000"
    container_name: petstore-app
    environment:
      - HOST_UID=1000
      - HOST_GID=1000
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./_docker/nginx/backend.conf:/etc/nginx/conf.d/backend.conf
      - ./:/var/www/html
    depends_on:
      - laravel
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge

